"""Generate the README's findings section from committed JSON.

The README is the first thing a reader sees, so its headline numbers must come
from the same committed results as everything else rather than being typed in
and left to drift. This script rewrites the block between the two marker
comments in ``README.md`` and changes nothing else.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from asla.analysis.abstention import glr_threshold  # noqa: E402
from asla.provenance import Source  # noqa: E402

REPO = Path(__file__).resolve().parents[1]
RESULTS = REPO / "results"
README = REPO / "README.md"

START = "<!-- BEGIN GENERATED FINDINGS -->"
END = "<!-- END GENERATED FINDINGS -->"


def load(relative: str) -> Any:
    return json.loads((RESULTS / relative).read_text(encoding="utf-8"))


def build() -> str:
    adversarial = load("adversarial/a1_independent_rederivation.json")
    dose = load("adversarial/a2_dose_response.json")
    theory_v2 = load("theory_v2/theory_v2.json")
    resolution = load("resolution/resolution_study.json")
    abstention = load("abstention/abstention_1B.json")
    allocation = load("allocation/allocation_1B.json")
    curvature = load("curvature/curvature_gate.json")
    common_mode = load("common_mode/common_mode_gate.json")

    real = theory_v2["FINDING_misspecification_is_structured"]["evidence"]["1_misspecification_is_real"]
    rho = dose["rank_correlations"]
    summary = resolution["summary"]
    coverage = abstention["coverage"]
    boot = coverage["bootstrap"]
    conf = coverage["conformal"]
    boot_centre = coverage["bootstrap_centring"]
    single = abstention["scored"]["single_scale_top_rung"]
    cost = next(
        (r for r in abstention["cost_of_correctness"] if r.get("seed_budget") == 3),
        None,
    )
    gate = curvature["gate"]
    adjudication = curvature["gate_adjudication"]
    tpp = curvature["alternative_explanations"]["tokens_per_param"]
    scope = curvature["confound_scope"]

    # The best (lowest) excess of any optimally-allocated arm over single-scale.
    excesses = [
        entry["scored"]["decision_optimal"]["excess_over_single_scale"]
        for entry in allocation["sweep"].values()
        if "scored" in entry and entry["scored"].get("decision_optimal", {}).get("excess_over_single_scale") is not None
    ]
    p4_gaps = [
        entry["max_cost_share_gap_decision_vs_estimation"]
        for entry in allocation["sweep"].values()
        if "max_cost_share_gap_decision_vs_estimation" in entry
    ]

    # Classify by the measured property (whether PC1 loadings share a sign),
    # not by suite name: the split is what the diagnostic asserts, so it should
    # be read off the data. Keep every assessment -- there is more than one per
    # suite/metric pair, and keying on the pair silently drops rows.
    offset_cvs = [
        a["shared_component_shape"]["loading_cv"]
        for a in common_mode["assessments"]
        if a["shared_component_shape"]["loadings_same_sign"]
    ]
    scaled_cvs = [
        a["shared_component_shape"]["loading_cv"]
        for a in common_mode["assessments"]
        if not a["shared_component_shape"]["loadings_same_sign"]
    ]

    # Headline metric for the project is C4 bits-per-token; name it explicitly
    # rather than taking whichever key happens to come first.
    headline_metric = "c4_en_bits_per_token"
    single_scale_rate = next(
        row["audit"]
        for row in adversarial["comparisons"][headline_metric]["rows"]
        if row["quantity"] == "single_scale_mis_selection"
    )

    z_threshold = glr_threshold(0.05, 300)
    t_three = glr_threshold(0.05, 300, n_seeds=3)
    t_ratio = Source.load("target_scoring/target_scoring.json")
    t_key = "student_t_recomputed.ratio_at_measured_df"
    t_fifty = glr_threshold(0.05, 300, n_seeds=50)
    rescoring = Source.load("target_scoring/rescoring.json")
    c4_rankers = rescoring.get("cells.c4_en_bits_per_token.rankers")
    reliably_different = sorted(name for name, row in c4_rankers.items() if row["verdict"] == "SURVIVES")
    within_noise = sorted(name for name, row in c4_rankers.items() if row["verdict"] != "SURVIVES")
    allocation_rows = rescoring.get("optimal_allocation.by_budget_fraction")
    allocation_within_noise = [row["budget_fraction"] for row in allocation_rows if row["verdict"] != "SURVIVES"]

    lines: list[str] = [
        START,
        "",
        "## Findings",
        "",
        "Generated by `scripts/render_readme_findings.py` from committed JSON in"
        " `results/`; every number below is reproducible by re-running the"
        " corresponding script. Pre-registrations live in `PREDICTIONS_TASK_*.md`"
        " and were committed before the numbers they score.",
        "",
        "### 1. On DataDecide, extrapolation never beat ranking at the top rung",
        "",
        f"Single-scale ranking at the largest fitted budget mis-selects"
        f" **{single_scale_rate:.2%}** of pairs on DataDecide ({headline_metric}). Across"
        f" {dose['n_matched_ladders']} matched ladders in a specification curve, plain"
        f" projection never beat it"
        f" (`max_excess_among_winning = {dose['max_excess_among_winning']:.1f}`). The"
        f" excess tracks the **lever arm**, not the number of fitted budgets:"
        f" Spearman **{rho['spearman_excess_vs_log_lever_arm']:+.3f}**"
        f" (p = {rho['spearman_excess_vs_log_lever_arm_p']:.1e}) against log lever arm,"
        f" versus {rho['spearman_excess_vs_budgets']:+.3f} against budget count.",
        "",
        "Scope: this is measured on DataDecide C4 bits-per-token with a 1B target,"
        " across every design and estimator we tested. It is not a proof that"
        " extrapolation can never help, and the regime where it should help --- a lever"
        " arm large enough that no run near the target exists --- is exactly where the"
        " ground truth needed to check it does not exist either.",
        "",
        "None of the alternatives we built beat a baseline that fits nothing and"
        " extrapolates nothing: better estimators (shared-exponent, empirical-Bayes"
        " shrinkage, ensemble, checkpoint-augmented), a better objective, and a better"
        " *ladder*. That is a statement about point estimates. Under expected-error"
        " scoring with candidates resampled (`results/target_scoring/rescoring.json`),"
        f" {', '.join(within_noise)} are indistinguishable from single-scale on C4;"
        f" only {', '.join(reliably_different)} differs reliably, and it is worse.",
        "",
        f"- **Optimal allocation.** Solving the cost-constrained transductive design"
        f" and evaluating at matched compute leaves an excess over single-scale of"
        f" **{min(excesses):+.3f} to {max(excesses):+.3f}** at the 1B target. Under"
        f" expected-error scoring the excess is reliable at reduced budgets and within"
        f" noise at budget fraction {', '.join(f'{v:g}' for v in allocation_within_noise)};"
        f" the optimised design never does better than single-scale.",
        f"- **Design for decision = design for estimation.** Under the linear model the"
        f" target-gap variance is exactly twice the target-level variance, so the two"
        f" objectives share an argmin. Measured: maximum cost-share difference"
        f" **{max(p4_gaps):.5f}** against a pre-registered threshold of 0.02. Changing"
        f" the design objective cannot change the design chosen, so it is not a lever.",
        "",
        "### 2. Model error dominates seed noise, and is structured in compute",
        "",
        f"Residual scatter of cell means about a fitted power law is"
        f" **{real['residual_scatter_over_seed_se']:.2f}x** the seed standard error, an"
        f" **{real['variance_inflation']:.2f}x** variance inflation, so the dominant"
        f" term in projection error is model error that more seeds do not shrink."
        f" (Finding 3 below shows a large part of the *out-of-range* component is a"
        f" ladder design confound rather than an inadequacy of the power law; this"
        f" in-range scatter is not explained by that confound.) A single"
        f" variance-inflation scalar cannot absorb it: `phi` varies"
        f" **2.7-8.9x** across ladders and under-predicts held-out structure by"
        f" **12x**.",
        "",
        f"Whether that error cancels in a *pairwise gap* is metric-dependent and"
        f" predictable in advance from the PC1 loading CV, which separates the suites"
        f" with no overlap: **{min(offset_cvs):.3f}-{max(offset_cvs):.3f}** for"
        f" offset-type metrics against **{min(scaled_cvs):.3f}-{max(scaled_cvs):.3f}**"
        f" for scaled-type ones.",
        "",
        "### 3. A large part of the extrapolation error is a ladder confound",
        "",
        f"Projections overshoot the observed 1B target by"
        f" **{gate['C3_quantitative_recovery']['mean_observed_overshoot']:+.4f}**, with"
        f" 24 of 25 recipes on the same side. Residual curvature is real and unanimous"
        f" (quadratic coefficient signed 25/25, p = "
        f"{gate['C1_sign_consistency']['sign_test_p']:.1e}; Spearman"
        f" {gate['C2_curvature_predicts_overshoot']['spearman_rho']:+.3f} against the"
        f" overshoot) but does **not** explain it: taking the curvature hypothesis at"
        f" face value removes only"
        f" **{adjudication['curvature_absolute_error_reduction']:.0%}** of the absolute"
        f" error.",
        "",
        f"The dominant source is a design confound. DataDecide's tokens-per-parameter"
        f" holds near 100 up to 90M and then drifts to"
        f" **{tpp['target']:.1f}** at the 1B target, correlating with log compute at"
        f" **{tpp['corr_log_tpp_with_log_compute']:+.2f}**, so a compute-only fit"
        f" attributes one effect to the other. Adding `log(tokens/param)` cuts absolute"
        f" projection error by"
        f" **{adjudication['tokens_per_param_absolute_error_reduction']:.0%}**.",
        "",
        f"The confound is common-mode: the two projection sets agree at Spearman"
        f" **{scope['spearman_between_projections']:.4f}**"
        f" ({scope['mis_selection_compute_only']:.2%} versus"
        f" {scope['mis_selection_with_tokens_per_param']:.2%} mis-selection), so it"
        f" shifts the level without reordering. Selection results are unaffected;"
        f" coverage and centring results are what it explains.",
        "",
        "### 4. Current confidence statements fail in two quantified ways",
        "",
        f"- **Precisely wrong, not merely narrow.** Bootstrap projection intervals"
        f" cover the observed target **{boot['coverage']:.0%}** of the time"
        f" ({int(round(boot['coverage'] * boot['n']))}/{boot['n']}) against a"
        f" {coverage['nominal_coverage']:.0%} nominal level. The band is"
        f" **{boot_centre['error_to_width_ratio']:.2f}x narrower than its own centring"
        f" error**. Conformal covers {conf['coverage']:.0%} by being"
        f" **{conf['median_width'] / boot['median_width']:.0f}x wider** at the same"
        f" centring, not by being better placed.",
        f"- **A nominal guarantee that is not the achieved one.** Nominal"
        f" delta = 0.05 becomes an effective"
        f" **{boot['effective_error_at_nominal_delta_0_05']:.3f}** under bootstrap"
        f" widths.",
        "",
        "### 5. Certification is free where it matters, and unavailable where it is tempting",
        "",
        f"A delta-PAC rule that abstains rather than guessing is cheap at the top of"
        f" the ladder: at the 1B target with 3 seeds it certifies"
        f" **{cost['n_certified']} of {cost['n_pairs']}** pairs with"
        f" **{cost['certified_wrong']} certified errors**, declining only"
        f" **{cost['fraction_of_correct_calls_abstained']:.1%}** of the calls the"
        f" baseline gets right (single-scale mis-selection here is"
        f" {single['mis_selection']:.2%}).",
        "",
        f"The complement is the constraint. Across the audited leaderboards,"
        f" **{summary['total_unresolved_at_3_seeds']} of"
        f" {summary['total_adjacent_pairs']}** adjacent orderings"
        f" ({summary['total_unresolved_at_3_seeds'] / summary['total_adjacent_pairs']:.1%})"
        f" are not resolvable at the seed budget actually used, and"
        f" **{summary['total_unidentifiable_at_any_budget']}** are unidentifiable at any"
        f" budget. A leaderboard that always returns a ranking is running a procedure"
        f" with no correctness guarantee.",
        "",
        "### 6. A reference-distribution defect in standard practice",
        "",
        f"With `n` seeds the standard deviation is estimated from `n` points, so the"
        f" reference distribution is Student's t on `2n-2` degrees of freedom. Under a"
        f" Bonferroni correction over 300 comparisons at delta = 0.05, the t quantile"
        f" at 3 seeds is **{t_three:.2f}** against the normal's **{z_threshold:.2f}**,"
        f" a factor of {t_three / z_threshold:.2f}x even in the equal-variance best case."
        f" With the Welch degrees of freedom measured per pair on DataDecide, the"
        f" Gaussian threshold is anti-conservative by a median of"
        f" **{t_ratio.number(t_key + '.median'):.2f}x**"
        f" ({t_ratio.number(t_key + '.p10'):.2f}x to {t_ratio.number(t_key + '.p90'):.2f}x,"
        f" 10th to 90th percentile) at exactly the seed count leaderboards use. The"
        f" best case closes to {t_fifty / z_threshold:.2f}x only by 50 seeds. Anyone"
        f" reporting significance on a 3-seed grid with a Gaussian threshold inherits"
        f" this. See `results/confidence/STUDENT_T_DEFECT.md`.",
        "",
        "### Reproducing these numbers",
        "",
        "Every document under `results/` is rendered from committed JSON by a script"
        " in `scripts/`. To check that none has drifted from the results it claims to"
        " be generated from:",
        "",
        "```bash",
        "python scripts/verify_reproducibility.py --verbose",
        "```",
        "",
        "The studies themselves are re-runnable but slow (hours on a laptop); each"
        " driver takes `--fast` for a smoke test and `--resume` to reuse completed"
        " work. The JSON they produce is committed, so the documents and this section"
        " can be regenerated without re-running them.",
        "",
        "### Reading order",
        "",
        "| document | what it contains |",
        "| --- | --- |",
        "| `NOVELTY_CHECK.md` | positioning against transductive bandits, SL2, and misspecified BAI |",
        "| `FORMULATION.md` | the problem as transductive pure exploration, with the `h*` recovery |",
        "| `results/allocation/RESULTS.md` | optimal allocation scored against pre-registered P1-P5 |",
        "| `results/abstention/RESULTS.md` | abstention versus delta and budget, scored against A1-A5 |",
        "| `results/curvature/RESULTS.md` | the curvature gate and the tokens-per-parameter confound, C1-C7 |",
        "| `results/confidence/` | the Student-t defect and the two confidence failures |",
        "| `results/consolidated/` | the measurement-artifact practice and model-error structure |",
        "",
        END,
    ]
    return "\n".join(lines)


def main() -> None:
    text = README.read_text(encoding="utf-8")
    block = build()
    if START in text and END in text:
        before = text[: text.index(START)]
        after = text[text.index(END) + len(END) :]
        README.write_text(before + block + after, encoding="utf-8")
    else:
        anchor = "## Install"
        index = text.index(anchor)
        README.write_text(text[:index] + block + "\n\n" + text[index:], encoding="utf-8")
    print(f"updated {README}")


if __name__ == "__main__":
    main()
