"""Generate the two-axes selection-stability section from committed JSON.

The section this renders is a reframing of H2. We had one word, "stable", doing
two jobs. Separating them is the contribution:

  data/corpus interventions:  scale-stable    (DataDecide), metric-UNstable (compute-multipliers)
  recipe interventions:       metric-stable   (compute-multipliers), scale-stability untested

Both halves are measured on independent suites and neither requires a compute
ladder, which is why this survives the Task 0 gate failure.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from asla.provenance import Source

REPO = Path(__file__).resolve().parents[1]

# Which family each metric belongs to. The interesting comparison is ACROSS
# families: two benchmark suites agreeing with each other says little, while a
# perplexity metric disagreeing with a benchmark is the finding.
METRIC_FAMILY = {
    "native_heldout_nll": "perplexity",
    "heldout7_mean_nll": "perplexity",
    "olmes10": "benchmark",
    "alt8": "benchmark",
}
METRIC_LABELS = {
    "native_heldout_nll": "native NLL",
    "heldout7_mean_nll": "held-out-7 NLL",
    "olmes10": "OLMES10",
    "alt8": "Alt-8",
}
AXIS_LABELS = {"corpus": "corpus (data)", "recipe": "recipe (model)"}


def _pair_label(key: str) -> str:
    left, right = key.split("|")
    kind = "cross-family" if METRIC_FAMILY[left] != METRIC_FAMILY[right] else "within-family"
    return f"{METRIC_LABELS.get(left, left)} vs {METRIC_LABELS.get(right, right)} ({kind})"


def _cross_family(block: dict[str, Any]) -> list[float]:
    return [
        value
        for key, value in block["pairwise_rank_spearman"].items()
        if METRIC_FAMILY[key.split("|")[0]] != METRIC_FAMILY[key.split("|")[1]]
    ]


def render() -> str:
    gate = Source.load("external/compute_multipliers_gate.json")
    agreement = gate.get("metric_agreement_at_top_budget")
    coverage = gate.get("coverage")
    counter = Source.load("external/counterexample_delphi.json")

    corpus = agreement["corpus"]
    recipe = agreement["recipe"]

    lines: list[str] = []
    lines.append("# Two axes of selection failure, and they live in different classes")
    lines.append("")
    lines.append("Generated by `scripts/render_selection_stability.py` from committed JSON.")
    lines.append("")
    lines.append(
        "**This section is exploratory.** Nothing in it was pre-registered: the measurement was "
        "made while assessing whether an external suite could close a different gap, and it is "
        "reported because it reframes a hypothesis we had already committed to, not because it "
        "confirms one."
    )
    lines.append("")

    lines.append("## The conflation")
    lines.append("")
    lines.append(
        "Our H2 predicted that data interventions are the *scale-stable* class --- low crossover "
        "risk, so small-scale rankings survive extrapolation --- and that recipe interventions "
        "are the crossover-prone one. The DataDecide result is consistent with the first half: on "
        "the data axis, ranking at the top rung is hard to beat, which is what a class with few "
        "crossovers should look like."
    )
    lines.append("")
    lines.append(
        "That framing used one word, *stable*, for two different properties. A class can be "
        "stable under a change of **scale** and unstable under a change of **metric**, and "
        "nothing ties the two together. Separating them is the point of this section."
    )
    lines.append("")

    lines.append("## Measurement")
    lines.append("")
    lines.append(
        f"The compute-multipliers suite releases {coverage['n_rows_public']} runs at a single "
        f"budget of {coverage['budgets_public'][0]:.0e} FLOPs: "
        f"{recipe['n_candidates']} recipes on a fixed corpus and "
        f"{corpus['n_candidates']} corpora under a fixed recipe, each with "
        f"{corpus['n_seeds_per_candidate']} seeds, scored on four metrics. Comparing *rankings* "
        f"across metrics needs no compute ladder, so this is computable from the public artifact "
        f"even though the ladder needed for an extrapolation test is not released."
    )
    lines.append("")
    lines.append("### Rank correlation between metrics, by axis")
    lines.append("")
    pairs = sorted(set(corpus["pairwise_rank_spearman"]) | set(recipe["pairwise_rank_spearman"]))
    lines.append("| metric pair | corpus axis | recipe axis |")
    lines.append("| --- | --- | --- |")
    for key in pairs:
        left = corpus["pairwise_rank_spearman"].get(key)
        right = recipe["pairwise_rank_spearman"].get(key)
        lines.append(
            f"| {_pair_label(key)} | "
            f"{'n/a' if left is None else f'{left:+.3f}'} | "
            f"{'n/a' if right is None else f'{right:+.3f}'} |"
        )
    lines.append("")
    corpus_cross = _cross_family(corpus)
    recipe_cross = _cross_family(recipe)
    lines.append(
        f"Over all pairs the corpus axis ranges {corpus['min_pairwise_spearman']:+.3f} to "
        f"{corpus['max_pairwise_spearman']:+.3f} and the recipe axis "
        f"{recipe['min_pairwise_spearman']:+.3f} to {recipe['max_pairwise_spearman']:+.3f}. The "
        f"comparison that matters is **across metric families**, since two benchmark suites "
        f"agreeing with each other is not evidence about endpoint choice. Restricted to the four "
        f"perplexity-versus-benchmark pairs, the corpus axis runs "
        f"**{min(corpus_cross):+.3f} to {max(corpus_cross):+.3f}** against the recipe axis's "
        f"**{min(recipe_cross):+.3f} to {max(recipe_cross):+.3f}**: on the corpus axis a "
        f"perplexity ranking carries essentially no information about a benchmark ranking."
    )
    lines.append("")

    lines.append("### Who wins depends on what you measure")
    lines.append("")
    lines.append("| metric | best corpus | best recipe |")
    lines.append("| --- | --- | --- |")
    for metric, label in METRIC_LABELS.items():
        lines.append(
            f"| {label} | `{corpus['winner_by_metric'].get(metric, 'n/a')}` | "
            f"`{recipe['winner_by_metric'].get(metric, 'n/a')}` |"
        )
    lines.append("")
    lines.append(
        f"**{corpus['n_distinct_winners']} distinct corpora win under four metrics; "
        f"{recipe['n_distinct_winners']} distinct recipes do.** On the corpus axis the "
        f"perplexity-style and benchmark-style metrics disagree almost completely: a broad-web "
        f"corpus wins on native NLL, a different broad-web corpus on held-out-7, and an "
        f"educational-filtered corpus on both benchmark suites. On the recipe axis the newest "
        f"recipe wins under three of four."
    )
    lines.append("")

    lines.append("## The reframing")
    lines.append("")
    lines.append("| intervention class | stable under change of scale | stable under change of metric |")
    lines.append("| --- | --- | --- |")
    lines.append(
        "| **data / corpus** | yes (DataDecide: ranking at the top rung is hard to beat) | "
        f"**no** (cross-family Spearman {min(corpus_cross):+.3f} to "
        f"{max(corpus_cross):+.3f}, {corpus['n_distinct_winners']} winners) |"
    )
    lines.append(
        "| **recipe / model** | **untested** (no seeded public ladder) | "
        f"yes (cross-family Spearman {min(recipe_cross):+.3f} to "
        f"{max(recipe_cross):+.3f}, {recipe['n_distinct_winners']} winners) |"
    )
    lines.append("")
    lines.append(
        "These are two independent failure modes, each dominant in a different class, each "
        "measured on an independent suite, and neither requiring a compute ladder. The class our "
        "own theory calls the safe one for extrapolation is the *unsafe* one for choosing an "
        "endpoint --- so a practitioner who follows H2 and picks a corpus from small-scale runs "
        "has avoided one hazard and walked into the other."
    )
    lines.append("")
    lines.append(
        "The practical consequence is that a selection procedure needs to declare its endpoint "
        'before it reports an accuracy. On the corpus axis, "which corpus is best" is not '
        "well-posed without naming the metric: the answer changes with it, and the disagreement "
        "is not small."
    )
    lines.append("")

    lines.append("## Scope and limits")
    lines.append("")
    lines.append(
        f"One budget ({coverage['budgets_public'][0]:.0e} FLOPs), "
        f"{corpus['n_candidates']} corpora and {recipe['n_candidates']} recipes, "
        f"{corpus['n_seeds_per_candidate']} seeds each, one suite. Rank correlations on seven "
        "items are noisy, and the winner counts are descriptive rather than tested against a null "
        "of metric exchangeability. The direction of the contrast is large enough to report; the "
        "magnitudes are not precise. This is also a single-budget snapshot, so it says nothing "
        "about whether the metric disagreement grows or shrinks with scale --- which is the "
        "obvious next question and needs the same unreleased ladder."
    )
    lines.append("")
    lines.append(
        "The recipe axis's scale-stability remains untested, which is the open question recorded "
        "in `OPEN_QUESTIONS.md`. Note what this section does *not* claim: that the recipe axis is "
        "scale-unstable. It is unmeasured, and the honest statement of H2 is now that one of its "
        "two halves has support and the other has never been tested."
    )
    lines.append("")

    lines.append("## Relation to the extrapolation counterexample")
    lines.append("")
    accuracy = counter.get("level_accuracy_does_not_imply_decision_accuracy")
    tightest = accuracy["by_accuracy"][0]
    lines.append(
        f"The same distinction explains why Open Athena's Delphi result and ours are compatible. "
        f"They predict a single configuration's loss at 1e23 FLOPs within "
        f"{counter.number('source.reported_accuracy_at_target'):.1%}, extrapolating "
        f"{counter.integer('source.extrapolation_factor')}x past their fit. They never rank "
        f"candidates: every fit is for one recipe, and their Attempt 1 versus Attempt 2 "
        f"comparison is a diagnosis of why a recipe mis-extrapolated, not a selection between "
        f"candidates."
    )
    lines.append("")
    lines.append(
        f"A level guarantee does not become a decision guarantee. At their tightest reported "
        f"accuracy, {tightest['level_accuracy']:.1%} of the loss level is "
        f"{tightest['tolerance_in_metric_units']:.4f} in our metric's units, which exceeds the "
        f"true gap for **{tightest['pairs_with_gap_below_tolerance']} of {accuracy['n_pairs']} "
        f"pairs ({tightest['fraction_unresolved']:.1%})** on DataDecide at 1B. Applied "
        f"independently per candidate, an error bound that good would still leave those "
        f"orderings undetermined --- and our measured mis-selection rate is smaller than that "
        f"fraction. That is consistent with the error being substantially common-mode, which "
        f"the loading diagnostic measures directly, but it does not require it: a bound that "
        f"is loose relative to the typical error gives the same result. "
        f"Whether it cancels is the question this project measures, and the answer is "
        f"metric-dependent, which is the same axis this section is about."
    )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=REPO / "results" / "external" / "SELECTION_STABILITY.md")
    args = parser.parse_args()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(), encoding="utf-8")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
