"""Cross-check the Signal-and-Noise C4-EN bits-per-byte grid against the DataDecide harvest.

Writes ``results/signal_and_noise/agreement.json`` and ``SIGNAL_AND_NOISE.md``.
Every number in the markdown is read from the JSON. Single-seed source:
no bootstrap intervals and no crossover significance are reported here.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from asla.analysis.fits import project_ranking, truth_ranking  # noqa: E402
from asla.analysis.metrics import decision_metrics  # noqa: E402
from asla.analysis.tuning import single_scale_pairwise_agreement  # noqa: E402
from asla.cli import _sha256_file, _write_json_atomically  # noqa: E402
from asla.data.io import load_runs  # noqa: E402

SN_TABLE = Path("data/signal_and_noise_datadecide_c4_bpb.parquet")
DD_TABLE = Path("data/datadecide_runs.parquet")


def _compute_of(df: pd.DataFrame, label: str) -> float:
    values = df[df["scale_label"] == label]["compute"].unique()
    if len(values) != 1:
        raise ValueError(f"{label!r} maps to {len(values)} compute values")
    return float(values[0])


def metric_agreement(sn: pd.DataFrame, dd: pd.DataFrame) -> list[dict[str, Any]]:
    """Per scale: pairwise order agreement between S&N bits/byte and DataDecide seed-mean bits/token."""

    out = []
    for label in [s for s in sn["scale_label"].unique()]:
        if label not in set(dd["scale_label"]):
            continue
        a = sn[sn["scale_label"] == label].set_index("intervention")["bpb"]
        b = dd[dd["scale_label"] == label].groupby("intervention")["bpb"].mean()
        common = sorted(set(a.index) & set(b.index))
        metrics = decision_metrics(a.loc[common], b.loc[common], k=1)
        out.append(
            {
                "scale_label": label,
                "n_recipes": len(common),
                "pairwise_agreement": metrics["pairwise_acc"],
                "kendall_tau": metrics["kendall_tau"],
                "same_winner": bool(metrics["top1_acc"]),
            }
        )
    return out


def duplicate_check(sn: pd.DataFrame, a: str, b: str) -> dict[str, Any]:
    """Report whether two recipes carry identical values (a mislabelled-release check)."""

    x = sn[sn["intervention"] == a].set_index("scale_label")["bpb"]
    y = sn[sn["intervention"] == b].set_index("scale_label")["bpb"]
    common = sorted(set(x.index) & set(y.index))
    return {
        "a": a,
        "b": b,
        "scales": common,
        "abs_diff": {label: float(abs(x.loc[label] - y.loc[label])) for label in common},
        "any_identical": bool(any(np.isclose(x.loc[label], y.loc[label], rtol=0, atol=1e-9) for label in common)),
    }


def flip_profile(sn: pd.DataFrame, target_label: str = "1B") -> list[dict[str, Any]]:
    target = _compute_of(sn, target_label)
    out = []
    for label in sn.drop_duplicates("scale_label").sort_values("compute")["scale_label"]:
        if label == target_label:
            continue
        res = single_scale_pairwise_agreement(sn, _compute_of(sn, label), target)
        out.append(
            {
                "scale_label": label,
                "compute_ratio_to_target": _compute_of(sn, label) / target,
                "n_pairs": res["n_pairs"],
                "n_flips": res["n_disagreeing"],
                "flip_rate": 1.0 - res["pairwise_agreement"],
            }
        )
    return out


def projection_check(sn: pd.DataFrame, target_label: str = "1B") -> dict[str, Any]:
    target = _compute_of(sn, target_label)
    budgets = tuple(sorted(float(b) for b in sn[sn["compute"] < target]["compute"].unique()))
    projected = project_ranking(sn, budgets, target)
    truth = truth_ranking(sn, target)
    metrics = decision_metrics(projected, truth, k=1)
    return {
        "fit_budget_labels": [str(sn[np.isclose(sn["compute"], b)]["scale_label"].iloc[0]) for b in budgets],
        "pairwise_acc": metrics["pairwise_acc"],
        "top1_acc": metrics["top1_acc"],
        "regret": metrics["regret"],
        "projected_winner": str(projected.index[0]),
        "true_winner": str(truth.index[0]),
    }


def render(results: dict[str, Any]) -> str:
    lines = [
        "# Signal-and-Noise as a third source",
        "",
        "Generated by `scripts/run_signal_and_noise_check.py`; numbers come from "
        "`results/signal_and_noise/agreement.json`.",
        "",
        "Source: `allenai/signal-and-noise` `core` split, `paloma_c4_en` **bits per byte** for the final checkpoint "
        "of 25 DataDecide recipes x 9 scales (one evaluated run per cell; see the module docstring for the seed "
        "labelling). This is the only public table found with a true bits-per-byte metric for DataDecide, and it "
        "was produced by a different evaluation pipeline than the DataDecide release, so agreement between the two "
        "is an independent check of the harvest.",
        "",
        "## Agreement with the DataDecide harvest (C4-EN bits/token, seed mean) at each scale",
        "",
        "| scale | recipes | pairwise order agreement | Kendall tau | same winner |",
        "|---|---|---|---|---|",
    ]
    for row in results["metric_agreement"]:
        lines.append(
            f"| {row['scale_label']} | {row['n_recipes']} | {100 * row['pairwise_agreement']:.1f}% | "
            f"{row['kendall_tau']:.3f} | {'yes' if row['same_winner'] else 'no'} |"
        )
    dup = results["duplicate_check"]
    lines += [
        "",
        f"Mislabelling check: `{dup['a']}` versus `{dup['b']}` (both carry `DataDecide-dolma1_6plus` model paths at "
        f"some sizes in the release) - identical values at any scale: {'yes' if dup['any_identical'] else 'no'}; "
        f"absolute differences: " + ", ".join(f"{k} {v:.4f}" for k, v in dup["abs_diff"].items()) + ".",
        "",
        "## Single-scale order flips to 1B on this table",
        "",
        "| scale | scale / 1B compute | pairs | flipped | flip rate |",
        "|---|---|---|---|---|",
    ]
    for row in results["flip_profile"]:
        lines.append(
            f"| {row['scale_label']} | {row['compute_ratio_to_target']:.2e} | {row['n_pairs']} | {row['n_flips']} | "
            f"{100 * row['flip_rate']:.1f}% |"
        )
    pc = results["projection_check"]
    lines += [
        "",
        "## Projection ranker on this table",
        "",
        f"Fit budgets {', '.join(pc['fit_budget_labels'])} -> target 1B: pairwise decision accuracy "
        f"{100 * pc['pairwise_acc']:.1f}%, projected winner `{pc['projected_winner']}`, measured winner "
        f"`{pc['true_winner']}`, regret {pc['regret']:.4f} bits/byte. 750M is on-trajectory in this release "
        "(~110 tokens/param) and is included as a fit budget.",
        "",
        "Single seed per cell: no intervals, no crossover significance. C4-EN bits per byte is in-distribution for "
        "the `C4` recipe (see FIRST_AUDIT.md caveats).",
        "",
        "## Inputs",
        "",
    ]
    for path, digest in results["inputs"].items():
        lines.append(f"- `{path}` sha256 `{digest}`")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="results/signal_and_noise")
    parser.add_argument("--report", default="SIGNAL_AND_NOISE.md")
    args = parser.parse_args(argv)
    sn = load_runs(SN_TABLE)
    dd = load_runs(DD_TABLE)
    results = {
        "inputs": {str(SN_TABLE): _sha256_file(SN_TABLE), str(DD_TABLE): _sha256_file(DD_TABLE)},
        "metric_agreement": metric_agreement(sn, dd),
        "duplicate_check": duplicate_check(sn, "Dolma1.7", "Dolma1.6++"),
        "flip_profile": flip_profile(sn),
        "projection_check": projection_check(sn),
    }
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    _write_json_atomically(results, out / "agreement.json")
    Path(args.report).write_text(render(results), encoding="utf-8")
    print(f"wrote {out / 'agreement.json'} and {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
